### ISSUE TITLE
HA OS

### ISSUE THREAD

**Issue by PierreScerri** [mykhailog/hacs_waveshare_ups_hat#3]
Hi

Will this work with Home assistant OS?

in 'Directions for installing smbus support on Raspberry Pi' the terminal does not have 'sudo raspi-config'

Thank you.

**Comment by fraserp** [comment]
I used this for my HassOS based setup and I now have it working: https://community.home-assistant.io/t/add-on-hassos-i2c-configurator/264167

**Comment by keithr59** [comment]
Alternatively, I used the ENABLE I2C WITH AN SD CARD READER instructions in the Home Assistant Common Tasks - Operating System documentation: https://www.home-assistant.io/common-tasks/os/

**Comment by mykhailog** [comment]
> Alternatively, I used the ENABLE I2C WITH AN SD CARD READER instructions in the Home Assistant Common Tasks - Operating System documentation: https://www.home-assistant.io/common-tasks/os/

> I used this for my HassOS based setup and I now have it working: https://community.home-assistant.io/t/add-on-hassos-i2c-configurator/264167

thanks, added both to readme
